### ISSUE TITLE
Interface not working

### ISSUE THREAD

**Issue by tulbord** [BlueFinBima/DCS-Helios-MFD#1]
I'm having problems with the interfaces.
When trying to add an interface, the error message appears and then the blank window.

**Comment by tulbord** [comment]
![image](https://github.com/BlueFinBima/DCS-Helios-MFD/assets/78508590/7426fb0e-9a99-45af-8302-b4d8c20faf37)

**Comment by tulbord** [comment]
![image](https://github.com/BlueFinBima/DCS-Helios-MFD/assets/78508590/8d860667-9c12-4158-b27c-ac088395889f)

**Comment by tulbord** [comment]
![image](https://github.com/BlueFinBima/DCS-Helios-MFD/assets/78508590/a95bb559-c798-4ca6-a028-a4c8d2854def)

**Comment by BlueFinBima** [comment]
raised on the wrong repo and the wrong project.
